server.port=8080
spring.data.mongodb.uri=mongodb+srv://sailfishsupport_db_user:x4E6UBRnl548qqvk@sailfishdb.v3bvyte.mongodb.net/sailfish_db?appName=SailfishDB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sailfishsupport@gmail.com
spring.mail.password=iser rrqt lntj ugxb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
